filter:
    path: [src/*]
    excluded_paths: [vendor/*, tests/*]
checks:
    php:
        code_rating: true
        duplication: true
tools:
    external_code_coverage: true
    php_mess_detector:
        enabled: true
    php_cs_fixer:
        enabled: true
        config:
            level: psr2
    php_analyzer:
        enabled: false
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            excluded_paths:
                - 'tests/*'
                - 'vendor/*'
    php_pdepend: true
    php_cpd:
       enabled: true
       excluded_dirs: [vendor, tests]
before_commands:
    - "composer install --dev --prefer-source"
