language: php

php:
  - 5.5
  - 5.4
  - 5.3

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover

before_install:
  - composer install --prefer-source --no-interaction --dev

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover