language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3

before_script:
  - composer install --prefer-source --no-interaction --dev
  - mkdir -p php/extensions && cd php/extensions && git clone https://github.com/nicolasff/phpredis && cd phpredis && phpize && echo "Configuring phpredis..." && ./configure > /dev/null && echo "Building phpredis..." && make -j4 > /dev/null && echo "Installing phpredis..." && sudo make install > /dev/null && cd ../../..
  - echo 'extension=redis.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover